import express from 'express';
import {CreateGroup, createTicketBasicInfo, getGroups, getUserGroupCapabilities,updateTicketMedia,updateTicketAddOns,updateTicketDetails,updateTicketTerms,submitTicket,getAllGroupTicketId,getTicketById,deleteTicket,viewTickets } from '../services/ticket.service.js';
import { protect } from '../middlewares/auth.js';
const router = express.Router();
router.use(protect);
router.post('/create-event/:groupId', createTicketBasicInfo);
router.post('/create-group', CreateGroup);
router.get('/get-groups', getGroups);
router.get('/user-group-capabilities', getUserGroupCapabilities);
router.post('/update-ticket-media', updateTicketMedia);
router.post('/ticket-addons', updateTicketAddOns);
router.post('/update-ticket-details', updateTicketDetails);
router.post('/ticket-terms', updateTicketTerms);
router.post('/submit-ticket', submitTicket);
router.get('/get-all-tickets', getAllGroupTicketId);
router.get('/get-ticket/:ticketId', getTicketById);
router.delete('/delete-ticket', deleteTicket);
router.get('/view-tickets', viewTickets);
export default router;
